/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalc extends javax.swing.JFrame {
    //variables restringidas - privada
    private String entrada="";
    private int numero1, numero2;
    private String operador;
    /**
     * Creates new form jfrmCalc
     */
    public jfrmCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtcant = new javax.swing.JTextField();
        jbt7 = new javax.swing.JButton();
        jbt8 = new javax.swing.JButton();
        jbt9 = new javax.swing.JButton();
        jbt4 = new javax.swing.JButton();
        jbt5 = new javax.swing.JButton();
        jbt6 = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt0 = new javax.swing.JButton();
        jbtsum = new javax.swing.JButton();
        jbtac = new javax.swing.JButton();
        jbtmul = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jbtdiv = new javax.swing.JButton();
        jbtigu = new javax.swing.JButton();
        jbtres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtcant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtcant.setText("0");
        jtxtcant.setEnabled(false);

        jbt7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt7.setText("7");
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });

        jbt8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt8.setText("8");
        jbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt8ActionPerformed(evt);
            }
        });

        jbt9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt9.setText("9");
        jbt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt9ActionPerformed(evt);
            }
        });

        jbt4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt4.setText("4");
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });

        jbt5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt5.setText("5");
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });

        jbt6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt6.setText("6");
        jbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt6ActionPerformed(evt);
            }
        });

        jbt1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt1.setText("1");
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });

        jbt2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt2.setText("2");
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });

        jbt0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt0.setText("0");
        jbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt0ActionPerformed(evt);
            }
        });

        jbtsum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtsum.setText("+");
        jbtsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsumActionPerformed(evt);
            }
        });

        jbtac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtac.setText("ac");
        jbtac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtacActionPerformed(evt);
            }
        });

        jbtmul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtmul.setText("*");
        jbtmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmulActionPerformed(evt);
            }
        });

        jbt3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbt3.setText("3");
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });

        jbtdiv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtdiv.setText("/");
        jbtdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdivActionPerformed(evt);
            }
        });

        jbtigu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtigu.setText("=");
        jbtigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtiguActionPerformed(evt);
            }
        });

        jbtres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtres.setText("-");
        jbtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtsum))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt9)
                        .addGap(12, 12, 12)
                        .addComponent(jbt0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtdiv))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbt1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbt2)
                            .addGap(11, 11, 11)
                            .addComponent(jbt3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtmul)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtigu)))
                    .addComponent(jtxtcant))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jtxtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt7)
                    .addComponent(jbt8)
                    .addComponent(jbt9)
                    .addComponent(jbtdiv)
                    .addComponent(jbt0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt4)
                    .addComponent(jbt5)
                    .addComponent(jbt6)
                    .addComponent(jbtres)
                    .addComponent(jbtsum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt1)
                    .addComponent(jbt2)
                    .addComponent(jbtmul)
                    .addComponent(jbt3)
                    .addComponent(jbtigu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtac)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+7;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt8ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+8;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt8ActionPerformed

    private void jbt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt9ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+9;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt9ActionPerformed

    private void jbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt0ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+0;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt0ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+4;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+5;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt6ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+6;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt6ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+1;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+2;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+3;
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbtsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsumActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="+";
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbtsumActionPerformed

    private void jbtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtresActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="-";
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbtresActionPerformed

    private void jbtdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdivActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="/";
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbtdivActionPerformed

    private void jbtmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmulActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="*";
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbtmulActionPerformed

    private void jbtiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtiguActionPerformed
        // TODO add your handling code here:
        double result;
        numero2=Integer.parseInt(entrada);
        jtxtcant.setText("");
        if (operador.equals("+")) {
            result=numero1+numero2;
            entrada=String.valueOf(result);
            jtxtcant.setText(entrada);
        }
        if (operador.equals("-")) {
            result=numero1-numero2;
            entrada=String.valueOf(result);
            jtxtcant.setText(entrada);
        }
        if (operador.equals("*")) {
            result=numero1*numero2;
            entrada=String.valueOf(result);
            jtxtcant.setText(entrada);
        }
        if (operador.equals("/")) {
            result=numero1/numero2;
            entrada=String.valueOf(result);
            jtxtcant.setText(entrada);
        }
    }//GEN-LAST:event_jbtiguActionPerformed

    private void jbtacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtacActionPerformed
        // TODO add your handling code here:
        entrada="0";
        jtxtcant.setText(entrada);
    }//GEN-LAST:event_jbtacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt0;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JButton jbt6;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbt8;
    private javax.swing.JButton jbt9;
    private javax.swing.JButton jbtac;
    private javax.swing.JButton jbtdiv;
    private javax.swing.JButton jbtigu;
    private javax.swing.JButton jbtmul;
    private javax.swing.JButton jbtres;
    private javax.swing.JButton jbtsum;
    private javax.swing.JTextField jtxtcant;
    // End of variables declaration//GEN-END:variables
}
